language: node_js

node_js:
  - 14
  - 12
  - 10

branches:
  only:
  - develop
  - "/^release\\/.*/"

install:
  - npm install -g typescript
  - npm install -g aws-cdk
  - cd ${TRAVIS_BUILD_DIR}/packages/lambda-nodejs
  - npm install
  - cd ${TRAVIS_BUILD_DIR}/packages/lambda
  - npm install

script:
  - cd ${TRAVIS_BUILD_DIR}/packages/lambda-nodejs
  - npm test
  - cd ${TRAVIS_BUILD_DIR}/packages/lambda
  - npm test

notifications:
  email: false
  slack: $SLACK_SECRET
